package sourceprobe

import (
	"fmt"
	"strings"
)

func renderJobSummary(report *DailyReport) string {
	var b strings.Builder
	fmt.Fprintf(&b, "### Source health probe\n\n")
	fmt.Fprintf(&b, "- Executed at: %s\n", report.Summary.ExecutedAt.UTC().Format("2006-01-02T15:04:05Z"))
	fmt.Fprintf(&b, "- Run date: %s\n", report.Summary.RunDate)
	fmt.Fprintf(&b, "- Datasets probed: %d\n", report.Summary.TotalDatasets)
	fmt.Fprintf(&b, "- OK: %d · Warning: %d · Critical: %d\n", report.Summary.OKCount, report.Summary.WarningCount, report.Summary.CriticalCount)
	fmt.Fprintf(&b, "- Updated samples: %d\n", report.Summary.UpdatedCount)
	fmt.Fprintf(&b, "- Deprecated (2+ days): %d\n\n", report.Summary.DeprecatedCount)

	if len(report.Alerts) == 0 {
		b.WriteString("All official source links responded to sample GET probes.\n")
		return b.String()
	}

	b.WriteString("### Source health alerts\n\n")
	for _, alert := range report.Alerts {
		fmt.Fprintf(&b, "- **%s** (%s, day %d): %s\n", alert.DatasetID, alert.Severity, alert.ConsecutiveFailureDays, alert.Message)
		for _, url := range alert.Endpoints {
			fmt.Fprintf(&b, "  - %s\n", url)
		}
	}
	return b.String()
}

func renderCriticalAlerts(report *DailyReport) string {
	critical := make([]SourceAlert, 0)
	for _, alert := range report.Alerts {
		if alert.Severity == SeverityCritical {
			critical = append(critical, alert)
		}
	}

	if len(critical) == 0 {
		return "# Critical source health alerts\n\nNo critical source failures.\n"
	}

	var b strings.Builder
	b.WriteString("# Critical source health alerts\n\n")
	b.WriteString("| Dataset | Days | Message | Endpoints |\n")
	b.WriteString("|---------|------|---------|----------|\n")
	for _, alert := range critical {
		endpoints := strings.Join(alert.Endpoints, "<br>")
		fmt.Fprintf(&b, "| `%s` | %d | %s | %s |\n", alert.DatasetID, alert.ConsecutiveFailureDays, alert.Message, endpoints)
	}
	return b.String()
}

func renderPRBody(report *DailyReport) string {
	var b strings.Builder
	b.WriteString("## Source health daily probe\n\n")
	b.WriteString(renderJobSummary(report))
	b.WriteString("\n\nSee `data/source-health-reports/latest.json` for full outcomes.\n")
	return b.String()
}

func renderSourceHealthDoc(report *DailyReport) string {
	var b strings.Builder
	b.WriteString("# Source link health\n\n")
	b.WriteString("> Auto-generated by `source-health-bot` — do not edit manually.\n\n")
	fmt.Fprintf(&b, "**Last run:** %s (UTC)\n\n", report.Summary.ExecutedAt.UTC().Format("2006-01-02T15:04:05Z"))
	fmt.Fprintf(&b, "| Metric | Value |\n|--------|-------|\n")
	fmt.Fprintf(&b, "| Datasets probed | %d |\n", report.Summary.TotalDatasets)
	fmt.Fprintf(&b, "| OK | %d |\n", report.Summary.OKCount)
	fmt.Fprintf(&b, "| Warning | %d |\n", report.Summary.WarningCount)
	fmt.Fprintf(&b, "| Critical | %d |\n", report.Summary.CriticalCount)
	fmt.Fprintf(&b, "| Updated samples | %d |\n", report.Summary.UpdatedCount)
	fmt.Fprintf(&b, "| Deprecated/unreachable | %d |\n\n", report.Summary.DeprecatedCount)

	if len(report.Updated) > 0 {
		b.WriteString("## Updated samples (hash changed)\n\n")
		for _, id := range report.Updated {
			fmt.Fprintf(&b, "- `%s`\n", id)
		}
		b.WriteString("\n")
	}

	if len(report.Deprecated) > 0 {
		b.WriteString("## Deprecated or unreachable\n\n")
		for _, id := range report.Deprecated {
			fmt.Fprintf(&b, "- `%s`\n", id)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Maintenance\n\n")
	b.WriteString("When a link fails for 2+ consecutive days:\n\n")
	b.WriteString("1. Verify the official portal manually.\n")
	b.WriteString("2. Update `configs/catalog/*.yaml` `source_url` if moved.\n")
	b.WriteString("3. Update [docs/OFFICIAL-SOURCES.md](OFFICIAL-SOURCES.md).\n")
	b.WriteString("4. Re-run `make source-health-bot` locally to confirm recovery.\n\n")
	b.WriteString("Reports archive: `data/source-health-reports/daily/`.\n")
	return b.String()
}
